# Generated by Django 2.0.5 on 2019-02-26 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0003_auto_20190226_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='id',
        ),
        migrations.AddField(
            model_name='personal',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='regno',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
