# Generated by Django 2.0.5 on 2019-03-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20190226_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='dept',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='regno',
            new_name='RegNo',
        ),
    ]
