# Generated by Django 2.0.5 on 2019-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20190304_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='Batch',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
