# Generated by Django 2.0.5 on 2019-03-04 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_personal_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='BloodGroup',
            field=models.CharField(default='none', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='Course',
            field=models.CharField(default='none', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='Gender',
            field=models.CharField(default='none', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='Section',
            field=models.CharField(default='none', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='StudentMailID',
            field=models.CharField(default='none', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='StudentMobNo',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
