# Generated by Django 2.0.5 on 2019-03-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20190304_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='StudentMailID',
            field=models.CharField(max_length=100),
        ),
    ]
