# Generated by Django 2.0.5 on 2019-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20190304_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='Address',
            field=models.CharField(default='0', max_length=500),
            preserve_default=False,
        ),
    ]
