# Generated by Django 2.0.5 on 2019-03-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_leave_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leavType',
            field=models.CharField(default='demo', max_length=50),
            preserve_default=False,
        ),
    ]
